/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    views: [
        'MyContainer'
    ],
    name: 'MyApp',

    launch: function() {
        this.facebookAppId = '343895802382049';

        //codigo de facebook:
        try{
            //FACEBOOK SDK
            //--------------------------------------------------------------------------------------------------------------------------------------
            window.fbAsyncInit = function() {
                // init the FB JS SDK
                FB.init({
                    appId      : '343895802382049', // App ID from the App Dashboard
                    channelUrl : '//www.didicr.com/channel.html', // Channel File for x-domain communication
                    status     : true, // check the login status upon init?
                    cookie     : true, // set sessions cookies to allow your server to access the session?
                    xfbml      : true  // parse XFBML tags on this page?
                });
            };
            testAPI = function(){
                FB.api('/me', function(response) {
                    Ext.Msg.alert('Aviso', 'Sesión iniciada correctamente.', Ext.emptyFn);
                    Ext.getCmp("botonDespliegueInfoPerfilUsuario").setText(response.name);
                    //---------------------------------------------------------------------------------------------------------------------------------------------------------------
                    Ext.getCmp("containerLogIn").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});
                    //Se carga LOAD el store para carousel y DiDiRapidos
                    Ext.getStore("storeCarouselInicio").load();
                    //Funcion para ir cambiando las imagenes en eventos
                    var funcionCambioEstadoCarousel = function() {
                        var task = Ext.create('Ext.util.DelayedTask', function() {
                            //console.log('hi');
                            Ext.getCmp("carouselEventos").next();
                            if(Ext.getCmp("carouselEventos").getActiveIndex()==Ext.getCmp("carouselEventos").getItems().length-2){Ext.getCmp("carouselEventos").setActiveItem(0);}
                            funcionCambioEstadoCarousel.call(this);
                        }, this);
                        task.delay(5000);
                    };
                    //Esta es la funcion que hace que cambien las imagenes en el carousel Inicio
                    funcionCambioEstadoCarousel();
                    //---------------------------------------------------------------------------------------------------------------------------------------------------------------        
                });
            };
            //login function
            login = function() {
                //    alert("fgey");
                FB.login(function(response) {
                    if (response.authResponse) {
                        // connected
                        //alert('Su información: '+response.name+','+response.authResponse.userID+','+response.authResponse.accessToken+','+response.authResponse.expiresIn+','+response.authResponse.signedRequest);
                        testAPI();
                    } else {
                        Ext.Msg.alert('Aviso', 'Sesión no iniciada.', Ext.emptyFn);
                    }
                });
            };
            // Load the SDK's source Asynchronously
            // Note that the debug version is being actively developed and might 
            // contain some type checks that are overly strict. 
            // Please report such bugs using the bugs tool.
            (function(d, debug){
                var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
                if (d.getElementById(id)) {return;}
                js = d.createElement('script'); js.id = id; js.async = true;
                js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
                ref.parentNode.insertBefore(js, ref);
            }(document, /*debug*/ false));
            //--------------------------------------------------------------------------------------------------------------------------------------
        }
        catch(e){
        }


        Ext.get('splashLoader').destroy();


        Ext.create('MyApp.view.MyContainer', {fullscreen: true});
    }

});
